# Generated by Django 2.2.7 on 2019-11-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('contraseña', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=16)),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
